# Generated by Django 5.0.6 on 2024-07-07 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business", models.BooleanField(default=False)),
                ("entertainment", models.BooleanField(default=False)),
                ("general", models.BooleanField(default=False)),
                ("health", models.BooleanField(default=False)),
                ("science", models.BooleanField(default=False)),
                ("sports", models.BooleanField(default=False)),
                ("technology", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
