# Generated by Django 5.0.6 on 2024-07-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preferences",
            old_name="user_id",
            new_name="user",
        ),
    ]
