# Generated by Django 5.0.6 on 2024-07-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_user_id_preferences_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferences",
            name="business",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="entertainment",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="general",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="health",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="science",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="sports",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="technology",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
