[project]
name = "uvconfig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black==24.4.2",
    "celery==5.4.0",
    "crispy-bootstrap5==2024.2",
    "django==5.0.6",
    "django-browser-reload==1.12.1",
    "django-celery-beat==2.8.1",
    "django-celery-results==2.5.1",
    "django-crispy-forms==2.2",
    "django-extensions>=4.1",
    "django-htmx==1.18.0",
    "django-money==3.5.4",
    "django-phonenumber-field==8.1.0",
    "django-timezone-field==7.1",
    "dotenv==0.9.9",
    "gitpython==3.1.44",
    "google==3.0.0",
    "google-api-core==2.24.2",
    "google-api-python-client==2.169.0",
    "google-auth==2.40.1",
    "google-auth-httplib2==0.2.0",
    "google-cloud-api-gateway==1.12.1",
    "google-geo-type==0.3.12",
    "google-maps-addressvalidation==0.3.18",
    "google-maps-routing==0.6.15",
    "googleapis-common-protos==1.70.0",
    "googlemaps==4.10.0",
    "phonenumbers==9.0.5",
    "pylance>=0.29.0",
    "pytz>=2025.2",
    "redis==5.0.8",
    "stripe>=12.5.1",
    "uv==0.7.12",
]
